node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io', '51467ee1-f0b0-4b4d-ba93-a7cc0a81938c') {
       def app = docker.build("andreabecerra/docker-nodejs-demo:${commit_id}", '.').push()
     }
   }
}